### ISSUE TITLE
About static application documentation

### ISSUE THREAD

**Issue by davidtong28** [neherlab/pan-genome-visualization#15]
Hi! I noticed that the version `2.0.0` has recently been released and upgraded this to a static application. All local server components were removed. However I cannot find the documentation for this new feature, just finding some new scripts replacing old scripts. As a new user I am unable to utilize either local server or static application. I'm wondering if the documentation will be updated soon. 
I am also wondering if it is possible for the local server to be kept as a feature for future releases.

Sincerely,

David

**Comment by davidtong28** [comment]
I was able to access the previous local server features via cloning an older branch:
`git clone -b aws-docker-merge-neherlab-master https://github.com/neherlab/pan-genome-visualization`

**Comment by ivan-aksamentov** [comment]
The new readme contains more up-to date instructions:

https://github.com/neherlab/pan-genome-visualization/blob/master/README.md

Feel free to give it a try and let us know how it goes!
